name: caixabank-procution-pipeline
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Run CI command
              run: npm ci

            
            - name: Run the tests
              run: npm run test

            - name: Build
              run: npm run build

            - name: Install Vercel CLI
              run: npm install -global vercel@latest
            #SET ENVIRONMENT IN VERCEL.
            #CREATE ENVIRONMENT IN VERCEL & BUILD IN VERCEL.
            # GITHUB.COM > SETTINGS > SECRETS AND VARIABLES > ACTIONS > ENVRIONEMENT SECRETS.
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
            
        
                